vars:
processes:    

  nolex-core:
    command: npm install && npm run dev
    ready_log_line: "###NOLEX READY###"
  
  nolex-gui:
    command: npm install && npm run dev
    working_dir: "./nolex-gui"
    depends_on:
      nolex-core:
        condition: process_log_ready