vars:
processes:
    
  nolex-core:
    command: npm install && npm run start
    ready_log_line: "###NOLEX READY###"
  
  nolex-gui:
    command: npm install && npm run build && npm run preview
    working_dir: "./nolex-gui"
    depends_on:
      nolex-core:
        condition: process_log_ready
